export const nombreVariables: Record<string, string> = {
  "Batt_Volt_Min": "Batt_Volt_Min",
  "CO": "CO",
  "CO_PPMV_HUARA_MIN": "CO",
  "CO_PPMV_EXOFVICTORIA_MIN": "CO",
  "CO_PPMV_COLPINTADOS_MIN": "CO",
  "Direccion_Viento": "DV",
  "DIRV": "DV",
  "Dirección del Viento": "DV",
  "DIRECCION_DEL_VIENTO_HUARA_MIN": "DV",
  "DIRECCION_DEL_VIENTO_EXOFVICTORIA_MIN": "DV",
  "DIRECCION_DEL_VIENTO_COLPINTADOS_MIN": "DV",
  "Humedad_Relativa": "HR",
  "Humedad Relativa": "HR",
  "HUMR": "HR",
  "MP10": "PM10",
  "MP-10 beta": "PM10",
  "PM10_HUARA_MIN": "PM10",
  "PM10_EXOFVICTORIA_MIN": "PM10",
  "PM10_COLPINTADOS_MIN": "PM10",
  "PM2.5": "PM2_5",
  "PM25": "PM2_5",
  "PM2.5_EXOFVICTORIA_MIN": "PM2_5",
  "PM2.5_COLPINTADOS_MIN": "PM2_5",
  "NO": "NO",
  "NO_PPBV_HUARA_MIN": "NO",
  "NO_PPBV_EXOFVICTORIA_MIN": "NO",
  "NO_PPBV_COLPINTADOS_MIN": "NO",
  "NO2": "NO2",
  "NOX_PPBV_HUARA_MIN": "NO2",
  "NOX_PPBV_EXOFVICTORIA_MIN": "NO2",
  "NOX_PPBV_COLPINTADOS_MIN": "NO2",
  "O3": "O3",
  "O3_HUARA_MIN": "O3",
  "Precipitacion": "PP",
  "Presion_Atmosferica": "PS",
  "PRESION_ATM_hPa_HUARA_MIN": "PS",
  "PRESION_ATM_hPa_EXOFVICTORIA_MIN": "PS",
  "PRESION_ATM_hPa_COLPINTADOS_MIN": "PS",
  "RADIACION_W/m2_HUARA_MIN": "RS",
  "PATM": "PS",
  "Radiacion_Solar": "RS",
  "RADS": "RS",
  "Radicion_solar": "Radiacion_Solar2",
  "Sigma_Thetha": "Sigma_Thetha",
  "SO2": "SO2",
  "SO2_PPBV_HUARA_MIN": "SO2",
  "SO2_PPBV_EXOFVICTORIA_MIN": "SO2",
  "SO2_PPBV_COLPINTADOS_MIN": "SO2",
  "Suministro": "Suministro",
  "TEMPERATURA_C_HUARA_MIN": "Temperatura",
  "TEMPERATURA_C_EXOFVICTORIA_MIN": "Temperatura",
  "TEMPERATURA_C_COLPINTADOS_MIN": "Temperatura",
  "Temperatura_Ambiente": "Temp_A",
  "TEMP": "Temp_A",
  "Temperatura interna": "Temp_I",
  "Ups": "Ups",
  "Velocidad_Viento": "VV",
  "VELV": "VV",
  "Velocidad del Viento": "VV",
  "VELOCIDAD_DEL_VIENTO_M/S_HUARA_MIN": "VV",
  "VELOCIDAD_DEL_VIENTO_M/S_EXOFVICTORIA_MIN": "VV",
  "HUMEDAD_PORCENTAJE_HUARA_MIN": "HP",
  "HUMEDAD_PORCENTAJE_EXOFVICTORIA_MIN": "HP",
  "HUMEDAD_PORCENTAJE_COLPINTADOS_MIN": "HP",
  "PLUVIOMETRO_MM_HUARA_MIN": "pluviometro"
};

export default nombreVariables;